import {StyleSheet} from 'react-native';

export default styles = StyleSheet.create({
  card: {
    width: '92%',
    backgroundColor: '#fff',
    borderRadius: 12,
    alignSelf: 'center',
    marginTop: 10,
    marginBottom: 10,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.1,
    shadowRadius: 6,
    elevation: 3,
  },
  postStatus: {
    position: 'absolute',
    top: -10,
    right: 12,
    backgroundColor: '#6AC75A',
    borderWidth: 1,
    borderColor: 'grey',
    borderRadius: 5,
    paddingHorizontal: 8,
    paddingVertical: 2,
  },
  headerContainer: {
    width: '100%',
    paddingLeft: 15,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderBottomWidth: 0.7,
    borderBottomColor: 'lightgrey',
  },
  imageContainer: {
    marginLeft: '8%',
  },
  loadImage: {
    height: 50,
    width: 50,
    marginTop: 7,
  },
  postedText: {
    fontSize: 9,
    marginTop: 3,
    color: '#000',
  },
  cardContent: {
    width: '100%',
    // paddingVertical: 10,
    flexDirection: 'row',
    paddingVertical: 5,
    paddingHorizontal: 5,
  },
  divider: {
    height: 1,
    backgroundColor: '#eee',
    marginVertical: 4,
  },
  leftContent: {
    width: '50%',
    alignItems: 'flex-start',
  },
  detailRow: {
    width: '100%',
    flexDirection: 'row',
    paddingVertical: 5,
  },
  shipperContainer: {
    width: '100%',
    flexDirection: 'row',
    paddingVertical: 5,
    paddingHorizontal: 5,
  },
  icon: {
    width: 18,
    height: 18,
    marginRight: 10,
  },
  shipperIcon: {
    width: 40,
    height: 40,
    marginRight: 10,
  },
  detailText: {
    color: 'black',
    fontSize: 12,
  },
  shipperText: {
    color: 'black',
    fontSize: 12,
    marginLeft: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  rateContainer: {
    marginTop: 20,
    backgroundColor: '#edf5ff',
    borderRadius: 30,
    padding: 2,
    paddingHorizontal: 8,
  },
  dateContainer: {
    marginTop: 10,
    backgroundColor: '#edf5ff',
    borderRadius: 30,
    padding: 5,
  },
  rateText: {
    fontSize: 11,
    color: 'black',
  },
  amountText: {
    fontSize: 18,
    alignSelf: 'center',
    color: 'black',
    fontWeight: '600',
  },
  totalFreightText: {
    fontSize: 12,
    alignSelf: 'center',
    color: 'black',
  },
  repostButton: {
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#edf5ff',
    paddingVertical: 8,
    borderRadius: 10,
    // borderBottomLeftRadius: 10,
    flexDirection: 'row',
  },
  repostButtonText: {
    color: 'blue',
    fontSize: 18,
    fontWeight: '600',
    marginLeft: 10,
  },
  waitingStatus: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 8,
    margin: 5,
    borderWidth: 1,
    borderColor: '#B2EBF2',
  },
  waitingStatusText: {
    color: '#000',
    marginLeft: 10,
  },
  lorryAttachment: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    paddingVertical: 10,
  },
  lorryAttachmentText: {
    color: '#000',
    marginLeft: 10,
  },
  requestButton: {
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#78f57c',
    marginLeft: 10,
    borderRadius: 6,
    flexDirection: 'row',
    padding: 5,
    margin: 5,
    paddingHorizontal: 12,
  },
  requestButtonText: {
    color: 'blue',
    fontSize: 14,
    fontWeight: '500',
    marginLeft: 5,
  },
  waitRequestContainer: {
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    marginTop: 5,
    marginBottom: 5,
    marginHorizontal: 10,
    paddingVertical: 5,
    paddingHorizontal: 20,
    borderRadius: 6,
    borderColor: 'grey',
    borderWidth: 1,
  },
  waitRequestText: {
    color: '#000',
    marginLeft: 10,
  },
  loadedRequestContainer: {
    alignItems: 'center',
    flexDirection: 'row',

    padding: 5,
  },
  loadedRequestText: {
    color: '#000',
    marginLeft: 10,
    textAlign: 'center',
    fontSize: 14,
  },
  acceptButtonContainer: {
    backgroundColor: 'green',
    padding: 5,
    marginTop: 10,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 8,
    marginLeft: 10,
  },
  buttonText: {
    color: 'white',
  },
  rejectButtonContainer: {
    backgroundColor: 'red',
    padding: 5,
    marginTop: 10,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 8,
    marginLeft: 10,
  },
  completionRequestButton: {
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#78f57c',
    marginLeft: 10,
    borderRadius: 6,
    flexDirection: 'row',
    padding: 5,
    margin: 5,
    paddingHorizontal: 25,
  },
  completionRequestButtonText: {
    color: 'blue',
    fontSize: 14,
    fontWeight: '500',
    marginLeft: 5,
  },
  completionMessage: {
    borderColor: 'green',
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    paddingVertical: 5,
    paddingHorizontal: 12,
    borderRadius: 5,
    margin: 5,
    borderWidth: 1,
  },
  completionMessageText: {
    color: 'green',
    fontSize: 13,
    fontWeight: '600',
    marginLeft: 5,
  },
  errorMessage: {
    borderColor: 'red',
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    paddingVertical: 5,
    paddingHorizontal: 12,
    borderRadius: 5,
    margin: 5,
    borderWidth: 1,
  },
  errorMessageText: {
    color: 'red',
    fontSize: 13,
    fontWeight: '600',
    marginLeft: 5,
  },
  statusBox: {
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    marginTop: 5,
    marginBottom: 5,
    paddingVertical: 5,
    paddingHorizontal: 20,
    borderRadius: 6,
    marginLeft: 5,
    borderColor: 'grey',
    borderWidth: 1,
  },
  statusText: {
    color: '#000',
    marginLeft: 10,
  },
  bidNowButton: {
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#c5e7eb',
    height: '20%',
    borderBottomRightRadius: 10,
    borderBottomLeftRadius: 10,
    flexDirection: 'row',
  },
  bidNowButtonText: {
    color: 'blue',
    fontSize: 18,
    fontWeight: '500',
    marginLeft: 5,
  },
  buttonContainer: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingBottom: 10,
  },
  actionButton: {
    padding: 7,
    marginTop: 10,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 8,
  },
  attachLorryButton: {
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#c5e7eb',
    width: '68%',
    borderRadius: 6,
    flexDirection: 'row',
    padding: 5,
    margin: 6,
  },
  attachLorryText: {
    color: 'blue',
    fontSize: 15,
    fontWeight: '500',
    marginLeft: 5,
  },
  disabledButton: {
    backgroundColor: '#C0C0C0', // Set your desired color for the disabled state
    opacity: 0.7, // Adjust the opacity to indicate it's disabled
  },
  waitingForAcceptanceContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    paddingVertical: 5,
    paddingHorizontal: 12,
    borderRadius: 5,
    margin: 5,
    borderWidth: 1,
    borderColor: 'grey',
  },
  waitingForAcceptanceText: {
    color: '#000',
    marginLeft: 10,
  },
  shareButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#203afa', // Primary theme color
    paddingVertical: 8,
    paddingHorizontal: 14,
    borderRadius: 20,
    elevation: 3,
  },
  shareButtonText: {
    color: '#fff',
    fontSize: 15,
    fontWeight: '600',
    marginLeft: 8,
  },
  shareIcon: {
    width: 22,
    height: 22,
    tintColor: 'white', // White icon color
  },
  emptyParkContainer: {
    padding: 5,
    flexDirection: 'row',
    // paddingVertical: 5,
    // paddingHorizontal: 5,
  },
  expectedRateContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 5,
    paddingHorizontal: 5,
  },
  cardContainer: {
    flexDirection: 'row',
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 10,
    // shadowColor: '#000',
    // shadowOffset: { width: 0, height: 2 },
    // shadowOpacity: 0.1,
    // shadowRadius: 3,
    // elevation: 3,
    // marginVertical: 6,
    // marginHorizontal: 10,
  },
  textContainer: {
    flex: 1,
    marginTop: '3.5%',
    marginLeft: '2%',
  },
  locationRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  // icon: {
  //   marginRight: 6,
  // },
  locationLabel: {
    fontSize: 12,
    color: '#888',
    fontWeight: '600',
    marginRight: 4,
  },
  locationText: {
    fontSize: 13,
    color: '#333',
    fontWeight: '600',
    flexShrink: 1,
  },
  lineContainer: {
    alignItems: 'flex-start',
    marginVertical: 4,
    marginLeft: '5%',
  },
  dottedLine: {
    borderStyle: 'dotted',
    borderWidth: 0.5,
    borderRadius: 1,
    width: '70%',
    borderColor: '#ccc',
  },
  postedTimeContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 4,
    paddingLeft: 24,
  },
  postedTimeText: {
    fontSize: 11,
    color: '#666',
    fontStyle: 'italic',
  },
  rightInfoContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8, // if using React Native 0.71+
  },
  distanceContainer: {
    backgroundColor: '#eee',
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 2,
    marginRight: 8,
  },
  distanceText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#000',
  },
  shareContainer: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 5,
    marginRight: 50,
  },
  topShareicon: {
    tintColor: '#9e9e9e',
    width: 20,
    height: 20,
    marginRight: 5,
  },
  // shareButton: {
  //   padding: 4,
  // },
  // shareIcon: {
  //   color: '#666',
  // },
});
